[project]
authors = ["Ryan Oates <ryanfullstack@icloud.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
description = "Add a short description here"
name = "openai_prompting"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
